language: r

r:
  - oldrel
  - release
  - devel

cache: packages
sudo: false
warnings_are_errors: false

r_packages:
  - roxygen2
  - testthat

addons:
  apt:
    packages:
      - libudunits2-dev
      - libv8-dev
      - libgdal1-dev
      - libproj-dev
      - libgeos-dev
      - libjq-dev
      - libprotobuf-dev
      - protobuf-compiler
