language: r
sudo: false
cache: packages
addons:
  apt:
    packages:
      - libudunits2-dev
      - libv8-dev
      - libgdal1-dev
      - libproj-dev
      - libgeos-dev
      - libjq-dev
      - libprotobuf-dev
